name: Deploy on Shah Trigger

on:
  push:
    branches:
      - master
      - 'copilot/**'
    paths:
      - 'shah.mdc'

jobs:
  trigger-deployment:
    name: Trigger N8N Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Trigger Docker Build and Push
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Triggering deployment workflow...');
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docker-build-push.yml',
              ref: context.ref,
              inputs: {
                push_enabled: 'true'
              }
            });
            console.log('Deployment workflow triggered successfully!');

      - name: Log deployment trigger
        run: |
          echo "=== Deployment Triggered ==="
          echo "Triggered by: ${{ github.actor }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
